# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 170e741da7b3714f8ee895cbd48a035c42e5d1532f8245d88e631adfc30b084a55940c161ec10ba7e637bac92fc4f8b2e57ce8a63b95be94ceae15886183b878

test:
  secret_key_base: f94c2b7044b8c48a7b6a8c216268587f70c43b13277b4d1bdce9ebe04429c4f3c12f84070a518fac91b1627588b8689a3fef3b3e6f04bca4761f1eb1da8d21b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
